version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 5
    reviewers:
      - "maxbarsukov"
    schedule:
      interval: "monthly"
